### ISSUE TITLE
The addon doesn't do anything

### ISSUE THREAD

**Issue by phaolo2** [fuzzykiller/download-cleaner-lite#10]
Firefox 108 x64, Windows 7 x64, i5 6600k

Settings:
- enabled: remove downloads after a delay (120 for example).
- disabled: remove downloads when starting.
- disabled: consider interrupted downloads as complete.

Result:
I can still see the downloads till 10 days ago..

**Comment by btzdnl** [comment]
Hi, thanks for reaching out. While I try to reproduce, a question: Those downloads that are still in your history, did you perform them while Download Cleaner Lite was already installed and enabled? Due to add-on API limitations, Download Cleaner Lite can only act on downloads it “witnessed”. Historical downloads are invisible to the add-on.

**Comment by phaolo2** [comment]
Yeah, the downloads history was older than the addon.
IMO you should write a warning on the addon page about this limitation.
Thanks for the support.

**Comment by btzdnl** [comment]
I have updated the add-on description on AMO for now. I will also add a hint to the add-on options page.

If you’re interested, the relevant bug is [1255507](https://bugzilla.mozilla.org/show_bug.cgi?id=1255507).

**Comment by btzdnl** [comment]
A new version (2.2) is on its way and will be available on AMO shortly.
